# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
import Config

config :phoenix_starter, PhoenixStarterWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {0, 0, 0, 0}, port: 4000],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "habpivcnlpohsazd4DSmn26jvAftxmZjQjn+xJ9ER/jzvTySWXP2lMRpZZ53hZBV",
  watchers: []

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"
config :phoenix_starter, dev_routes: true
config :phoenix, :stacktrace_depth, 20
config :phoenix, :plug_init_mode, :runtime

# Guardian configuration
config :arke_auth, ArkeAuth.Guardian,
       issuer: "arke_auth",
       verify_issuer: true,
       token_ttl: %{"access" => {7, :days}, "refresh" => {30, :days}},
       secret_key: "habpivcnlpohsazd4DSmn26jvAftxmZjQjn+xJ9ER/jzvTySWXP2lMRpZZ53hZBV"


# Leave to use  mix commands
config :arke_postgres, ArkePostgres.Repo,
  database: System.get_env("DB_NAME"),
  hostname: System.get_env("DB_HOSTNAME"),
  username: System.get_env("DB_USER"),
  password: System.get_env("DB_PASSWORD")
