name: Build phoenix_starter starter STAGING

on:
  workflow_dispatch:
  push:
    branches: ["staging"]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    concurrency:
      group: ci-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v3

      - name: Build & push Docker image 🐳
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: phoenix_starter
          tags: staging
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          buildArgs: MIX_ENV=${{ secrets.MIX_ENV_STAGING }}
        env:
          MIX_ENV: ${{ secrets.MIX_ENV_STAGING }}
